const hobbies = {
  COOKING: 'Готовка',
  DRAWING: 'Рисование',
  ANIME: 'Аниме',
  DORAMAS: 'Дорамы',
  VOCALOIDS: 'Вокалоиды',
  MUSIC_LISTENERS: 'Прослушивание музыки',
  MUSIC_COMPOSITORS: 'Композиторство',
  MUSIC_WRITERS: 'Сочинение текстов песен',
  GAMES: 'Игры',
  MOVIES: 'Фильмы',
  WALKING: 'Прогулки',
  NATURE: 'Природа',
  MUSIC_PLAYING: 'Игра на инструменте',
  STREAMS: 'Просмотр стримов',
  STREAMER: 'Стриминг',
  RUBIKS_CUBE: 'Кубик Рубика',
  LITERATURE: 'Литература',
  FANFICS: 'Фанфики',
  MANGA_COMICS: 'Манга/Комиксы',
  COLLECTIONNING: 'Коллекционирование',
  PROGRAMMING: 'Программирование',
  SPORT: 'Спорт',
  LANGUAGES: 'Изучение языков',
  WRITING: 'Сочинение стихов/написание книг',
  NURSING: 'Времяпрепровождение с детьми',
  TECHNIC: 'Техника',
  POLITICS: 'Политика',
  PROJECTS: 'Проектирование',
  _3D_GRAPHICS: '3D Графика',
  YOUTUBE_WATCHER: 'Просмотр YouTube',
  FURRY: 'Фурри',
  CYBER_SPORT: 'Киберспорт',
  TIKTOKER: 'Ведение Тиктока',
  WEAPONS: 'Оружие',
  SIGARETS: 'Сигареты',
  ANIMALS: 'Животные',
  PHOTOGRAPHING: 'Фотография',
  DANCING: 'Танцы',
  KNITTING: 'Вязание',
  PLANES: 'Самолеты',
  AUTO: 'Автомобили',
  THEATER: 'Театр',
  HUNTING: 'Охота',
  CLUBS: 'Клубы',
  SERIALS: 'Сериалы',
  WOOD_MAKING: 'Резка по дереву',
  _3D_MODELING: '3D моделирование',
  PSYCHOLOGY: 'Психология',
};

export default hobbies;
